baseURL = "https://tulis.netlify.app/"
title = "Fazikla"
theme = "gokarna"
languageCode = "id"
defaultContentLanguage = "id"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Fazikla"
  description = "Tempat menulis catatan."
  avatarURL = "avatar.webp"
  avatarSize = "size-s"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
  """
  #socialIcons = [
    #{name = "twitter", url = "https://example.com"},
    #{name = "linkedin", url = "https://example.com"},
    #{name = "stackoverflow", url = "https://example.com"},
    #{name = "dribbble", url = "https://example.com"},
    #{name = "instagram", url = "https://example.com"},
    #{name = "twitch", url = "https://example.com"},
  #]
  metaKeywords = ["fazikla"]

[menu]
  [[menu.main]]
    name = "Postingan"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tag"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Cari"
    url = "/pages/cari/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/pages/about/"
    weight = 4

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7
